from pathlib import Path
from html import escape
import json

OUT = Path('/home/joy/joy/linkedin-images-v2')
OUT.mkdir(parents=True, exist_ok=True)

POSTS = [
    dict(day=1, slug='ai-code-review', topic='AI Code Review', channel='PERSONAL / FIELD NOTE', template='forensic', kicker='CODE REVIEW / EVIDENCE 001', title='Clean code.\nDangerous code.', body='70% of this codebase was AI-generated. The vulnerabilities were human-readable.', stat='70%', label='AI-GENERATED', note='SQL concatenation\nHardcoded secrets\nMissing validation', cta='Would you ship this without a human review?'),
    dict(day=2, slug='exploit-window', topic='Exploit Window', channel='COMPANY / THREAT INTEL', template='bulletin', kicker='THREAT BULLETIN / 2026', title='The patch window\nis already closed.', body='Exploitation is landing before fixes are available.', stat='-7', label='DAYS TO EXPLOIT', note='DISCLOSURE → PATCH → EXPLOIT\nThe order changed.', cta='Can your team respond before the CVE drops?'),
    dict(day=3, slug='dev-vs-security', topic='Dev vs Security', channel='PERSONAL / FIELD NOTE', template='split', kicker='THE FRICTION IS TIMING', title='Security reviews\nfeel like a lecture.', body='The problem is not the review. It is when security enters the room.', left_title='WHAT DEVS HEAR', left=['Slow down.', 'Add more steps.', 'You are doing it wrong.'], right_title='WHAT SECURITY MEANS', right=['Ship faster.', 'Avoid the 3am call.', 'Make secure the easy path.'], cta='Where does your dev-security gap begin?'),
    dict(day=4, slug='api-security', topic='API Security', channel='COMPANY / DATA BRIEF', template='data', kicker='API SECURITY / FINDING 004', title='The breach\nstarts at the lock.', body='Broken authentication remains the most common API failure pattern.', stat='52%', label='API BREACHES', note='BROKEN AUTHENTICATION', bars=[('Broken auth', 52), ('No auth required', 59), ('Easy to exploit', 59)], cta='When did you last test your API auth?'),
    dict(day=5, slug='startup-cost', topic='Startup Cost', channel='PERSONAL / FIELD NOTE', template='field', kicker='RUNWAY INCIDENT / CASE NOTE', title='18 months of runway.\nOne breach cut it to 3.', body='The breach did not just expose data. It exposed the company’s future.', stat='18 → 3', label='MONTHS OF RUNWAY', note='$4M+ direct and indirect cost\nLost trust became the real bill.', cta='Is security in your foundation or on your roadmap?'),
    dict(day=6, slug='secure-sdlc', topic='Secure SDLC', channel='COMPANY / CONTROL ROOM', template='control', kicker='SECURE SDLC / CONTROL MAP', title='Security belongs\nbefore production.', body='A checklist after the breach is documentation. Controls before the code are prevention.', steps=['THREAT MODEL', 'SAST / EVERY PR', 'DEPENDENCY GATE', 'SECRET BLOCK', 'DAST / STAGING', 'CONTINUOUS TEST'], stat='06', label='CONTROL POINTS', cta='Which gate is missing from your pipeline?'),
    dict(day=7, slug='found-database', topic='Found Database', channel='PERSONAL / FIELD NOTE', template='forensic', kicker='CLOUD EXPOSURE / EVIDENCE 007', title='20 minutes to find it.\n3 years left open.', body='No exploit. No zero-day. A public bucket and a routine assessment.', stat='20 MIN', label='TIME TO FIND', note='PUBLIC S3 BUCKET\nTEMPORARY ACCESS\nPERMANENT EXPOSURE', cta='What exists outside your official infrastructure?'),
    dict(day=8, slug='cloud-misconfig', topic='Cloud Misconfig', channel='COMPANY / THREAT INTEL', template='bulletin', kicker='CLOUD SECURITY / ALERT 008', title='One checkbox.\nA public cloud.', body='Misconfiguration is not dramatic. That is why it survives.', stat='23%', label='OF CLOUD BREACHES', note='PRIVATE → PUBLIC\nOne setting. Infinite blast radius.', cta='How many misconfigured assets are in your cloud?'),
    dict(day=9, slug='iam-policy', topic='IAM Policy', channel='PERSONAL / FIELD NOTE', template='forensic', kicker='IDENTITY & ACCESS / EVIDENCE 009', title='Found this in\nproduction.', body='A wildcard policy. Created during an outage. Still active two years later.', stat='*', label='FULL ACCESS', note='ACTION: *\nRESOURCE: *\nEFFECT: ALLOW', code='{"Action":"*", "Resource":"*", "Effect":"Allow"}', cta='Is this in your AWS account?'),
    dict(day=10, slug='container-security', topic='Container Security', channel='COMPANY / CONTROL ROOM', template='control', kicker='CONTAINER SECURITY / LAYER MAP', title='Your code is clean.\nYour image is not.', body='A container is a stack. Scanning one layer does not secure the runtime.', steps=['BASE IMAGE', 'OS PACKAGES', 'APP DEPS', 'YOUR CODE', 'RUNTIME'], stat='47', label='CVEs IN BASE IMAGE', cta='Have you scanned the image—not just the code?'),
    dict(day=11, slug='private-vpc-myth', topic='Private VPC Myth', channel='PERSONAL / FIELD NOTE', template='split', kicker='MYTH / NETWORK PERIMETER', title='Private network\n≠ private data.', body='A private VPC controls one boundary. It does not make every service safe.', left_title='THE CLAIM', left=['Private VPC', 'No public IPs', 'So it is secure.'], right_title='THE PATHS OUT', right=['Public S3', 'NAT to internet', 'IAM: * permissions'], cta='What is actually private in your VPC?'),
    dict(day=12, slug='cloud-maturity', topic='Cloud Maturity', channel='COMPANY / CONTROL ROOM', template='control', kicker='CLOUD MATURITY / OPERATING MODEL', title='Where does your cloud\nsecurity actually stand?', body='The gap is not documentation. It is enforcement.', levels=[('01','REACTIVE'),('02','AWARE'),('03','DEFINED'),('04','MANAGED'),('05','OPTIMIZED')], stat='05', label='MATURITY LEVELS', cta='Which level is your organization really at?'),
    dict(day=13, slug='ai-reality-check', topic='AI Reality Check', channel='PERSONAL / OPINION', template='split', kicker='UNPOPULAR OPINION / AI', title='AI did not invent\nour security gaps.', body='It made the old failures faster, cheaper, and easier to scale.', left_title='NEW TOOLS', left=['AI code', 'AI phishing', 'AI malware'], right_title='OLD FAILURES', right=['SQL injection', 'Weak training', 'Missing visibility'], cta='Are we losing to AI—or to the same gaps?'),
    dict(day=14, slug='shadow-ai', topic='Shadow AI', channel='COMPANY / DATA LEAK', template='field', kicker='SHADOW AI / DATA TRAIL', title='You cannot secure\nwhat you cannot see.', body='An employee prompt can become a data-exposure path in seconds.', stat='$670K', label='ADDED BREACH COST', note='WORK EMAIL → PUBLIC AI →\nSENSITIVE DATA → UNKNOWN RETENTION', cta='What AI tools are your employees using?'),
    dict(day=15, slug='ai-code-test', topic='AI Code Test', channel='PERSONAL / DATA LAB', template='data', kicker='AI CODE TEST / BENCHMARK', title='None of the models\nwere safe by default.', body='The same prompts produced vulnerable code across every assistant tested.', stat='45–62%', label='VULNERABLE OUTPUT', note='COMMON FINDINGS\nSQLi · COMMAND INJECTION · SECRETS', bars=[('GPT-4o', 62), ('Claude 3', 58), ('Copilot', 55), ('Gemini', 48), ('GPT-5.2', 45)], cta='Are you reviewing AI-generated code?'),
    dict(day=16, slug='prompt-injection', topic='Prompt Injection', channel='COMPANY / THREAT INTEL', template='bulletin', kicker='AI SECURITY / ACTIVE THREAT', title='Prompts are\nthe new malware.', body='Trusted content becomes an instruction when the model processes it.', stat='90+', label='ORGANIZATIONS TARGETED', note='INJECT → GENERATE → EXFILTRATE\nThe payload is text.', cta='Is your AI hardened against prompt injection?'),
    dict(day=17, slug='ai-phishing', topic='AI Phishing', channel='PERSONAL / EXPERIMENT', template='split', kicker='PHISHING SIMULATION / SAME TARGETS', title='The old tells\ndo not work anymore.', body='Same company. Same employees. AI-crafted messages changed the result.', left_title='TRADITIONAL', left=['12%', 'Grammar tells', 'Generic request'], right_title='AI-CRAFTED', right=['54%', 'Perfect tone', 'Real context'], cta='Was the request expected—not just believable?'),
    dict(day=18, slug='ai-pipeline-security', topic='AI Pipeline Security', channel='COMPANY / CONTROL ROOM', template='control', kicker='AI DEPLOYMENT / SIX GATES', title='Deploying AI?\nSecure the pipeline.', body='The model is only one part of the attack surface.', steps=['MODEL ORIGIN', 'DATA VALIDATION', 'PROMPT TESTS', 'OUTPUT GUARDS', 'MONITORING', 'ROLLBACK'], stat='06', label='SECURITY GATES', cta='How many of these controls do you have?'),
    dict(day=19, slug='security-theater', topic='Security Theater', channel='PERSONAL / FIELD NOTE', template='field', kicker='SECURITY THEATER / OUTCOME CHECK', title='Activity is not\nrisk reduction.', body='A completed pentest is not the same thing as a remediated finding.', stat='≠', label='ACTIVITY / OUTCOME', note='PENTEST COMPLETE ≠ FINDINGS FIXED\nAUDIT PASSED ≠ ACTUALLY SECURE', cta='Are you measuring security or compliance?'),
    dict(day=20, slug='credential-theft', topic='Credential Theft', channel='COMPANY / THREAT BULLETIN', template='bulletin', kicker='IDENTITY SECURITY / THREAT DATA', title='Your identity\nis the perimeter.', body='Credential theft is industrialized—and session tokens can bypass MFA.', stat='1.8B', label='CREDENTIALS STOLEN', note='PASSWORDS · COOKIES · TOKENS\n276M included active sessions.', cta='Are your credentials in the next dataset?'),
    dict(day=21, slug='intern-story', topic='Intern Story', channel='PERSONAL / FIELD NOTE', template='field', kicker='AUTHENTICATION / FRESH EYES', title='3 senior engineers missed it.\n1 intern found it.', body='Expertise brings context. Fresh eyes bring questions.', stat='3 → 1', label='MISSED / FOUND', note='RACE CONDITION\n18 MONTHS UNDETECTED\n“Why does this work this way?”', cta='When did you last get fresh eyes on your code?'),
    dict(day=22, slug='incident-response', topic='Incident Response', channel='COMPANY / THREAT BULLETIN', template='bulletin', kicker='INCIDENT RESPONSE / COMMAND CLOCK', title='Your response window\nis smaller than a meeting.', body='From initial access to lateral movement, the clock is already running.', stat='29', label='MINUTES AVERAGE', note='14 MIN FASTEST\nDETECT → CONTAIN → INVESTIGATE', cta='Can your team respond inside the breakout window?'),
    dict(day=23, slug='stop-annual-pentests', topic='Stop Annual Pentests', channel='PERSONAL / OPINION', template='split', kicker='TESTING MODEL / THEN → NOW', title='Annual snapshots\nmiss continuous risk.', body='Pentests still matter. They cannot be the only layer anymore.', left_title='2020', left=['63 days', 'Static systems', 'Annual snapshot'], right_title='2026', right=['-7 days', 'Daily change', 'Continuous view'], cta='Is annual testing still enough on its own?'),
    dict(day=24, slug='mfa-not-enough', topic='MFA Not Enough', channel='COMPANY / CONTROL ROOM', template='control', kicker='IDENTITY SECURITY / BYPASS MAP', title='MFA is important.\nMFA alone is not security.', body='The control is only as strong as the routes around it.', steps=['PHISHING-RESISTANT', 'SESSION MONITORING', 'DEVICE TRUST', 'BEHAVIOR SIGNALS'], stat='59%', label='COMPROMISED ACCOUNTS HAD MFA', cta='Is your MFA phishing-resistant?'),
    dict(day=25, slug='axios-attack', topic='Axios Attack', channel='PERSONAL / INCIDENT LOG', template='forensic', kicker='SUPPLY CHAIN / INCIDENT LOG', title='19 minutes to infect.\n3 hours to discover.', body='A maintainer account became a distribution channel.', stat='19 MIN', label='TO SPREAD', note='00:00 ACCOUNT\n00:12 INJECT\n00:15 PUBLISH\n03:00 REMOVE', cta='Could your build pipeline detect this?'),
    dict(day=26, slug='2027-predictions', topic='2027 Predictions', channel='COMPANY / STRATEGIC BRIEF', template='forecast', kicker='SECURITY HORIZON / 2027', title='Prepare for the\nnext attack surface.', body='The future is uncertain. The signals are not.', predictions=['AI agents become attack vectors','Identity replaces the perimeter','Supply chain goes nation-state','Continuous security becomes default','Human-in-the-loop stays mandatory'], cta='What are you preparing for now?'),
    dict(day=27, slug='100-assessments', topic='100 Assessments', channel='PERSONAL / FIELD NOTES', template='field', kicker='FIELD NOTES / 100 ASSESSMENTS', title='The same five flaws\nkeep showing up.', body='The work is not glamorous. The basics still win.', stat='80%', label='CODEBASES / SAME FIVE', note='SQLi · XSS · BROKEN AUTH\nIDOR · SECRETS IN CODE', cta='Are these five findings in your codebase?'),
    dict(day=28, slug='supply-chain-stats', topic='Supply Chain Stats', channel='COMPANY / DATA LAB', template='data', kicker='SUPPLY CHAIN / YEAR OVER YEAR', title='Malicious packages\nare accelerating.', body='The dependency graph is becoming an attack distribution system.', stat='+73%', label='YEAR OVER YEAR', note='2024 → 263K\n2025 → 455K\nKNOWN MALWARE → 1.233M', bars=[('2024', 58), ('2025', 100)], cta='Are you scanning dependencies beyond direct imports?'),
    dict(day=29, slug='241-day-breach', topic='241-Day Breach', channel='PERSONAL / BREACH DATA', template='bulletin', kicker='BREACH RESPONSE / SLOW BURN', title='The breach is not\nthe explosion.', body='It is the 241 days of access before anyone knows it is there.', stat='241', label='DAYS TO IDENTIFY + CONTAIN', note='MAP → ESCALATE → PERSIST\nEight months of invisible access.', cta='Would you know if you were breached today?'),
    dict(day=30, slug='zero-trust-reality', topic='Zero Trust Reality', channel='COMPANY / ARCHITECTURE', template='split', kicker='ZERO TRUST / REALITY CHECK', title='Zero Trust is\nnot a\nproduct.', body='It is how access is designed, verified, limited, and continuously re-checked.', left_title='THE PITCH', left=['Buy the appliance', 'Deploy the agent', 'Now you have Zero Trust'], right_title='THE ARCHITECTURE', right=['Verify explicitly', 'Least privilege', 'Assume breach'], cta='Are you buying Zero Trust—or building it?'),
]

COMMON = '''
* {box-sizing:border-box} html,body{{margin:0;width:1080px;height:1080px}} body{{overflow:hidden;font-family:Arial,Helvetica,sans-serif}} .page{{position:relative;width:1080px;height:1080px;overflow:hidden}} .inner{{position:relative;z-index:2;height:100%;padding:58px 64px 46px}} .top{{display:flex;justify-content:space-between;align-items:center;height:35px;font:700 11px/1 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:1.8px;text-transform:uppercase}} .brand{{font:900 19px/1 Arial,sans-serif;letter-spacing:-.8px}} .brand span{{color:#ff5b36}} .channel{{font-size:10px;letter-spacing:1.4px}} .kicker{{font:800 12px/1 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:2px;text-transform:uppercase}} h1{{margin:0;white-space:pre-line;font:900 74px/.92 'Arial Narrow',Arial,sans-serif;letter-spacing:-4px;text-transform:uppercase}} .body{{font-size:18px;line-height:1.4}} .footer{{display:flex;justify-content:space-between;align-items:end;font:700 12px/1 ui-monospace,monospace;letter-spacing:1px;text-transform:uppercase}} .footer .url{{color:#ff8b69}}'''

CSS = '''
.forensic{{background:radial-gradient(500px 500px at 85% 4%,#26140e,transparent 70%),#0b0c0b;color:#eee9dc}} .forensic:before{{content:"";position:absolute;inset:0;opacity:.18;background-image:radial-gradient(rgba(255,255,255,.24) .5px,transparent .6px);background-size:5px 5px}} .forensic .channel,.forensic .kicker{{color:#ff6844}} .forensic .heading{{margin-top:78px;display:flex;justify-content:space-between;align-items:start}} .forensic h1{{margin-top:24px;max-width:700px}} .forensic .accent{{color:#ff5b36}} .forensic .summary{{margin-top:24px;color:#a7a093;font-size:16px;line-height:1.35}} .forensic .summary b{{color:#eee9dc}} .forensic .evidence{{margin-top:55px;border:1px solid #4d463f;border-left:7px solid #ff5b36;height:300px;background:#111210}} .forensic .e-head{{height:47px;padding:0 20px 0 24px;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #35352f;color:#aaa397;font:700 11px/1 ui-monospace,monospace;letter-spacing:1.5px;text-transform:uppercase}} .forensic .e-head b{{color:#ff9b78}} .forensic .e-body{{display:grid;grid-template-columns:48px 1fr 180px;height:252px}} .forensic .lines{{padding:24px 12px 0 0;border-right:1px solid #35352f;color:#5d5b54;text-align:right;font:16px/1.75 ui-monospace,monospace}} .forensic pre{{margin:23px 0 0 25px;color:#eee9dc;font:21px/1.7 ui-monospace,monospace;white-space:pre-wrap}} .forensic .key{{color:#a9c5ff}} .forensic .danger{{color:#ff5b36;font-weight:800}} .forensic .allow{{color:#d5ff4a;font-weight:800}} .forensic .note{{margin:32px 20px 0 0;padding-left:15px;border-left:1px solid #5b574e;color:#a7a093;font:11px/1.5 ui-monospace,monospace;text-transform:uppercase}} .forensic .note b{{display:block;color:#ff5b36;margin-bottom:10px}} .forensic .note strong{{display:block;margin-top:18px;color:#eee9dc;font:900 23px/.9 'Arial Narrow',Arial,sans-serif}} .forensic .metrics{{display:grid;grid-template-columns:1.2fr 1fr 1fr;margin-top:16px;border-top:1px solid #35352f;border-bottom:1px solid #35352f;height:80px}} .forensic .metric{{padding:15px 18px;border-right:1px solid #35352f}} .forensic .metric:last-child{{border:0}} .forensic .metric small{{display:block;color:#a7a093;font:700 10px/1 ui-monospace,monospace;letter-spacing:1.2px;text-transform:uppercase}} .forensic .metric strong{{display:block;margin-top:9px;color:#eee9dc;font:900 19px/1 'Arial Narrow',Arial,sans-serif;text-transform:uppercase}} .forensic .metric:first-child strong{{color:#ff5b36}} .forensic .metric:nth-child(2) strong{{color:#d5ff4a}} .forensic .footer{{margin-top:30px;color:#eee9dc}} .forensic .cta{{font:800 18px/1.1 Arial,sans-serif;letter-spacing:-.2px;text-transform:none}} .forensic .cta span{{color:#ff5b36}}
.bulletin{{background:#f0eee7;color:#10110f}} .bulletin:before{{content:"";position:absolute;left:0;top:0;bottom:0;width:18px;background:#ff4e3d}} .bulletin .inner{{padding-left:74px}} .bulletin .top{{border-bottom:2px solid #10110f}} .bulletin .brand span,.bulletin .channel,.bulletin .kicker{{color:#d83b2c}} .bulletin .hero{{margin-top:77px;display:grid;grid-template-columns:1fr 350px;gap:55px;align-items:end}} .bulletin .hero h1{{margin-top:24px;max-width:600px}} .bulletin .body{{max-width:530px;margin-top:25px;color:#57584f}} .bulletin .statbox{{height:300px;padding:25px 22px;border:2px solid #10110f;background:#ff4e3d;color:#f0eee7;display:flex;flex-direction:column;justify-content:space-between}} .bulletin .statbox small{{font:800 11px/1 ui-monospace,monospace;letter-spacing:1.6px;text-transform:uppercase}} .bulletin .statbox .stat{{font:900 145px/.8 'Arial Narrow',Arial,sans-serif;letter-spacing:-8px}} .bulletin .statbox b{{font:900 21px/1 'Arial Narrow',Arial,sans-serif;letter-spacing:-.5px;text-transform:uppercase}} .bulletin .bullet-list{{margin-top:63px;border-top:2px solid #10110f;border-bottom:2px solid #10110f}} .bulletin .bullet-row{{display:flex;align-items:center;min-height:75px;border-bottom:1px solid #9d9b91;font:800 18px/1.15 'Arial Narrow',Arial,sans-serif;text-transform:uppercase}} .bulletin .bullet-row:last-child{{border-bottom:0}} .bulletin .bullet-row i{{width:10px;height:10px;margin-right:17px;background:#ff4e3d;border-radius:50%}} .bulletin .footer{{margin-top:30px}} .bulletin .cta{{font:800 18px/1.1 Arial,sans-serif;letter-spacing:-.2px;text-transform:none}} .bulletin .cta span{{color:#d83b2c}}
.data{{background:#ebe8df;color:#111210}} .data:after{{content:"";position:absolute;inset:0;opacity:.4;background-image:linear-gradient(#c9c5ba 1px,transparent 1px),linear-gradient(90deg,#c9c5ba 1px,transparent 1px);background-size:54px 54px;mask-image:linear-gradient(to bottom,transparent 0%,black 30%,black 100%)}} .data .top{{border-bottom:1px solid #111210}} .data .brand span,.data .channel,.data .kicker{{color:#0a8b83}} .data .hero{{margin-top:70px;display:grid;grid-template-columns:430px 1fr;gap:70px;align-items:start}} .data h1{{margin-top:22px;max-width:480px;font-size:67px}} .data .body{{margin-top:25px;color:#5b5a52;max-width:390px}} .data .big-stat{{margin-top:40px;color:#0a8b83;font:900 125px/.75 'Arial Narrow',Arial,sans-serif;letter-spacing:-8px}} .data .big-label{{margin-top:14px;font:900 17px/1 'Arial Narrow',Arial,sans-serif;letter-spacing:.2px;text-transform:uppercase}} .data .chart{{margin-top:5px;padding:24px 22px 22px;border-left:2px solid #111210;border-bottom:2px solid #111210;min-height:330px;background:rgba(255,255,255,.4)}} .data .chart-title{{color:#5b5a52;font:800 11px/1 ui-monospace,monospace;letter-spacing:1.6px;text-transform:uppercase}} .data .bar-row{{display:grid;grid-template-columns:110px 1fr 45px;gap:11px;align-items:center;margin-top:25px;font:800 12px/1 ui-monospace,monospace}} .data .bar{{height:22px;background:#c9c5ba}} .data .bar i{{display:block;height:100%;background:#0a8b83}} .data .bar-row:nth-child(3n) .bar i{{background:#ff5b36}} .data .bar-value{{text-align:right}} .data .note{{margin-top:30px;padding-top:17px;border-top:1px solid #8b887e;color:#5b5a52;font:700 12px/1.45 ui-monospace,monospace;white-space:pre-line;text-transform:uppercase}} .data .footer{{margin-top:70px;border-top:1px solid #111210;padding-top:20px}} .data .cta{{font:800 18px/1.1 Arial,sans-serif;letter-spacing:-.2px;text-transform:none}} .data .cta span{{color:#ff5b36}}
.split{{background:#ded8ca;color:#111210}} .split:before{{content:"";position:absolute;top:0;bottom:0;left:0;width:51%;background:#101311}} .split .inner{{padding-bottom:42px}} .split .top{{position:relative;color:#eee9dc}} .split .brand{{color:#eee9dc}} .split .brand span{{color:#ff5b36}} .split .channel{{color:#ff9b78}} .split .hero{{position:relative;margin-top:74px}} .split .kicker{{color:#ff5b36}} .split h1{{margin-top:22px;max-width:460px;color:#eee9dc;font-size:68px;overflow-wrap:break-word}} .split .body{{max-width:450px;margin-top:25px;color:#aaa397}} .split .panels{{display:grid;grid-template-columns:1fr 1fr;gap:28px;margin-top:62px}} .split .panel{{min-height:245px;padding:24px 25px;border:1px solid #68655b}} .split .panel:first-child{{border-color:#716c62;background:#101311;color:#eee9dc}} .split .panel:last-child{{background:#ff5b36;color:#101311;border-color:#101311}} .split .panel h3{{margin:0 0 24px;font:800 12px/1 ui-monospace,monospace;letter-spacing:1.7px;text-transform:uppercase}} .split .panel ul{{margin:0;padding:0;list-style:none}} .split .panel li{{display:flex;gap:12px;margin:0 0 14px;font:800 21px/1.02 'Arial Narrow',Arial,sans-serif;text-transform:uppercase}} .split .panel li:before{{content:"→";font-family:monospace}} .split .panel:first-child li:before{{color:#ff5b36}} .split .panel:last-child li:before{{color:#101311}} .split .footer{{position:absolute;left:64px;right:64px;bottom:42px;padding-top:16px;border-top:1px solid #aaa397;color:#101311}} .split .cta{{color:#eee9dc!important;font:800 18px/1.1 Arial,sans-serif;letter-spacing:-.2px;text-transform:none}} .split .cta span{{color:#ff5b36}}
.field{{background:#e9e1cf;color:#171714}} .field:before{{content:"";position:absolute;inset:0;opacity:.55;background-image:repeating-linear-gradient(0deg,transparent 0,transparent 35px,rgba(76,90,78,.1) 36px)}} .field:after{{content:"FIELD NOTE";position:absolute;right:-55px;top:410px;color:rgba(216,59,44,.12);font:900 160px/.8 'Arial Narrow',Arial,sans-serif;letter-spacing:-11px;transform:rotate(90deg)}} .field .top{{border-bottom:2px solid #171714}} .field .brand span,.field .channel,.field .kicker{{color:#d83b2c}} .field .hero{{margin-top:75px;display:grid;grid-template-columns:1fr 340px;gap:52px;align-items:center}} .field h1{{margin-top:23px;max-width:620px;font-size:70px}} .field .body{{max-width:560px;margin-top:26px;color:#5b5a52}} .field .note-card{{margin-top:45px;padding:20px 23px;border:1px solid #777268;border-left:7px solid #d83b2c;background:rgba(255,255,255,.34);color:#5b5a52;font:800 12px/1.5 ui-monospace,monospace;white-space:pre-line;text-transform:uppercase}} .field .stat-card{{height:300px;padding:22px;border:2px solid #171714;background:#d83b2c;color:#e9e1cf;display:flex;flex-direction:column;justify-content:space-between;transform:rotate(2deg)}} .field .stat-card small{{font:800 11px/1 ui-monospace,monospace;letter-spacing:1.7px;text-transform:uppercase}} .field .stat{{font:900 90px/.8 'Arial Narrow',Arial,sans-serif;letter-spacing:-5px}} .field .stat-card b{{font:900 18px/1 'Arial Narrow',Arial,sans-serif;text-transform:uppercase}} .field .footer{{margin-top:74px;padding-top:17px;border-top:2px solid #171714}} .field .cta{{font:800 18px/1.1 Arial,sans-serif;letter-spacing:-.2px;text-transform:none}} .field .cta span{{color:#d83b2c}}
.control{{background:radial-gradient(600px 420px at 95% 10%,rgba(0,180,150,.12),transparent 70%),#0d211e;color:#e7eee6}} .control:before{{content:"";position:absolute;inset:0;opacity:.18;background-image:linear-gradient(rgba(154,235,203,.17) 1px,transparent 1px),linear-gradient(90deg,rgba(154,235,203,.17) 1px,transparent 1px);background-size:44px 44px}} .control .top{{border-bottom:1px solid #3c5b53}} .control .brand span,.control .channel,.control .kicker{{color:#67e6bd}} .control .hero{{margin-top:72px;display:flex;justify-content:space-between;align-items:end}} .control h1{{margin-top:23px;max-width:660px;font-size:70px}} .control .body{{max-width:600px;margin-top:25px;color:#a5bbb0}} .control .statbox{{width:220px;height:160px;padding:20px;border:1px solid #67e6bd;background:#132d28;text-align:right}} .control .stat{{color:#67e6bd;font:900 77px/.8 'Arial Narrow',Arial,sans-serif;letter-spacing:-4px}} .control .statbox b{{display:block;margin-top:19px;color:#e7eee6;font:800 11px/1.2 ui-monospace,monospace;letter-spacing:1.2px;text-transform:uppercase}} .control .pipeline{{display:grid;grid-template-columns:repeat(6,1fr);gap:8px;margin-top:60px}} .control .step{{position:relative;min-height:155px;padding:16px 10px;border:1px solid #3c5b53;background:#132d28;display:flex;align-items:end;color:#d4e7dc;font:800 12px/1.1 ui-monospace,monospace;letter-spacing:.5px;text-transform:uppercase}} .control .step:before{{content:"";position:absolute;left:10px;top:15px;width:23px;height:23px;border:1px solid #67e6bd;border-radius:50%}} .control .step:after{{content:"✓";position:absolute;left:17px;top:18px;color:#67e6bd;font:700 14px/1 monospace}} .control .step:not(:last-child){{border-right-color:#67e6bd}} .control .footer{{margin-top:69px;padding-top:18px;border-top:1px solid #3c5b53}} .control .cta{{font:800 18px/1.1 Arial,sans-serif;letter-spacing:-.2px;text-transform:none}} .control .cta span{{color:#67e6bd}}
.forecast{{background:#171426;color:#f2efe8}} .forecast:before{{content:"";position:absolute;inset:0;opacity:.22;background-image:linear-gradient(#74688e 1px,transparent 1px),linear-gradient(90deg,#74688e 1px,transparent 1px);background-size:53px 53px}} .forecast .top{{border-bottom:1px solid #74688e}} .forecast .brand span,.forecast .channel,.forecast .kicker{{color:#c996ff}} .forecast .hero{{margin-top:75px;display:grid;grid-template-columns:400px 1fr;gap:78px}} .forecast h1{{margin-top:22px;font-size:70px}} .forecast .body{{margin-top:26px;color:#b9aec8}} .forecast .horizon{{margin-top:10px;color:#c996ff;font:800 12px/1 ui-monospace,monospace;letter-spacing:2px;text-transform:uppercase}} .forecast .predictions{{padding-top:9px;border-top:1px solid #74688e}} .forecast .pred{{display:grid;grid-template-columns:38px 1fr;gap:16px;align-items:start;min-height:72px;padding:15px 0;border-bottom:1px solid #4c425c}} .forecast .num{{color:#c996ff;font:900 25px/1 'Arial Narrow',Arial,sans-serif}} .forecast .pred strong{{font:800 18px/1.15 'Arial Narrow',Arial,sans-serif;letter-spacing:-.2px;text-transform:uppercase}} .forecast .pred p{{margin:6px 0 0;color:#9c8faa;font:12px/1.2 ui-monospace,monospace}} .forecast .footer{{margin-top:75px;padding-top:18px;border-top:1px solid #74688e}} .forecast .cta{{font:800 18px/1.1 Arial,sans-serif;letter-spacing:-.2px;text-transform:none}} .forecast .cta span{{color:#c996ff}}
'''


def esc(v):
    return escape(str(v), quote=True)

def title_html(title):
    lines = title.split('\n')
    if len(lines) == 1: return esc(lines[0])
    return '<br>'.join(esc(x) for x in lines)

def footer(d):
    return f'<footer class="footer"><div class="cta">{esc(d["cta"])} <span>→</span></div><div class="url">zerosight360.com</div></footer>'

def top(d):
    return f'<header class="top"><div class="brand">ZERO<span>SIGHT</span>360</div><div class="channel">{esc(d["channel"])}</div></header>'

def forensic(d):
    code = d.get('code', '{\n  "Action": "*",\n  "Resource": "*",\n  "Effect": "Allow"\n}')
    code_html = esc(code).replace('&quot;', '"').replace('"Action"','<span class="key">"Action"</span>').replace('"Resource"','<span class="key">"Resource"</span>').replace('"Effect"','<span class="key">"Effect"</span>').replace('"*"','<span class="danger">"*"</span>').replace('"Allow"','<span class="allow">"Allow"</span>')
    lines='01<br>02<br>03<br>04<br>05'
    note=esc(d.get('note','')).replace('\n','<br>')
    return f'''<div class="page forensic"><div class="inner">{top(d)}<section class="heading"><div><div class="kicker">{esc(d['kicker'])}</div><h1>{title_html(d['title'])}</h1><div class="summary">{esc(d['body'])}</div></div><div class="annotation">CRITICAL<br><small>REVIEW REQUIRED</small></div></section><section class="evidence"><div class="e-head"><span>EVIDENCE / {d['day']:03d}</span><b>ACTIVE / PRODUCTION</b></div><div class="e-body"><div class="lines">{lines}</div><pre>{code_html}</pre><div class="note"><b>FINDING</b>{note}<strong>{esc(d['label'])}</strong></div></div></section><section class="metrics"><div class="metric"><small>PRIMARY FINDING</small><strong>{esc(d['label'])}</strong></div><div class="metric"><small>TOPIC</small><strong>{esc(d['topic'])}</strong></div><div class="metric"><small>REQUIRED ACTION</small><strong>REVIEW NOW</strong></div></section>{footer(d)}</div></div>'''

def bulletin(d):
    note=esc(d.get('note','')).replace('\n','<br>')
    rows = ''.join(f'<div class="bullet-row"><i></i>{x}</div>' for x in [d.get('label','ACTIVE THREAT'), *d.get('note','').split('\n')[:2]])
    return f'''<div class="page bulletin"><div class="inner">{top(d)}<section class="hero"><div><div class="kicker">{esc(d['kicker'])}</div><h1>{title_html(d['title'])}</h1><div class="body">{esc(d['body'])}</div></div><div class="statbox"><small>LIVE FINDING</small><div class="stat">{esc(d['stat'])}</div><b>{esc(d['label'])}</b></div></section><section class="bullet-list">{rows}</section>{footer(d)}</div></div>'''

def data(d):
    bars=d.get('bars',[])
    chart=''.join(f'<div class="bar-row"><span>{esc(name)}</span><div class="bar"><i style="width:{val}%"></i></div><span class="bar-value">{val}%</span></div>' for name,val in bars)
    note=esc(d.get('note','')).replace('\n','<br>')
    return f'''<div class="page data"><div class="inner">{top(d)}<section class="hero"><div><div class="kicker">{esc(d['kicker'])}</div><h1>{title_html(d['title'])}</h1><div class="body">{esc(d['body'])}</div><div class="big-stat">{esc(d['stat'])}</div><div class="big-label">{esc(d['label'])}</div></div><div><div class="chart"><div class="chart-title">Evidence distribution / benchmark</div>{chart}</div><div class="note">{note}</div></div></section>{footer(d)}</div></div>'''

def split(d):
    left=''.join(f'<li>{esc(x)}</li>' for x in d.get('left',[]))
    right=''.join(f'<li>{esc(x)}</li>' for x in d.get('right',[]))
    return f'''<div class="page split"><div class="inner">{top(d)}<section class="hero"><div class="kicker">{esc(d['kicker'])}</div><h1>{title_html(d['title'])}</h1><div class="body">{esc(d['body'])}</div><div class="panels"><div class="panel"><h3>{esc(d['left_title'])}</h3><ul>{left}</ul></div><div class="panel"><h3>{esc(d['right_title'])}</h3><ul>{right}</ul></div></div></section>{footer(d)}</div></div>'''

def field(d):
    note=esc(d.get('note','')).replace('\n','<br>')
    return f'''<div class="page field"><div class="inner">{top(d)}<section class="hero"><div><div class="kicker">{esc(d['kicker'])}</div><h1>{title_html(d['title'])}</h1><div class="body">{esc(d['body'])}</div><div class="note-card">{note}</div></div><div class="stat-card"><small>FIELD NOTE / {d['day']:02d}</small><div class="stat">{esc(d['stat'])}</div><b>{esc(d['label'])}</b></div></section>{footer(d)}</div></div>'''

def control(d):
    if d.get('levels'):
        steps=[f'{a} / {b}' for a,b in d['levels']]
    else: steps=d.get('steps',[])
    cards=''.join(f'<div class="step">{esc(s)}</div>' for s in steps)
    return f'''<div class="page control"><div class="inner">{top(d)}<section class="hero"><div><div class="kicker">{esc(d['kicker'])}</div><h1>{title_html(d['title'])}</h1><div class="body">{esc(d['body'])}</div></div><div class="statbox"><div class="stat">{esc(d['stat'])}</div><b>{esc(d['label'])}</b></div></section><section class="pipeline">{cards}</section>{footer(d)}</div></div>'''

def forecast(d):
    rows=''.join(f'<div class="pred"><div class="num">{i:02d}</div><div><strong>{esc(x)}</strong><p>Signal to monitor / prepare now</p></div></div>' for i,x in enumerate(d['predictions'],1))
    return f'''<div class="page forecast"><div class="inner">{top(d)}<section class="hero"><div><div class="kicker">{esc(d['kicker'])}</div><h1>{title_html(d['title'])}</h1><div class="body">{esc(d['body'])}</div><div class="horizon">HORIZON / 12 MONTHS</div></div><div class="predictions">{rows}</div></section>{footer(d)}</div></div>'''

TEMPLATES={'forensic':forensic,'bulletin':bulletin,'data':data,'split':split,'field':field,'control':control,'forecast':forecast}
manifest=[]
for d in POSTS:
    body=TEMPLATES[d['template']](d)
    html='<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=1080, initial-scale=1"><title>ZeroSight360 V2 — '+esc(d['topic'])+'</title><style>'+(COMMON+CSS).replace('{{','{').replace('}}','}')+'</style></head><body>'+body+'</body></html>'
    html_path = OUT / ("v2_day%02d_%s.html" % (d["day"], d["slug"]))
    html_path.write_text(html, encoding='utf-8')
    manifest.append({k:v for k,v in d.items() if k not in {'left','right','steps','levels','bars','note','code'}})
(OUT/'manifest.json').write_text(json.dumps(manifest, indent=2), encoding='utf-8')
print(f'Generated {len(POSTS)} HTML sources in {OUT}')
